name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 7 * * 2'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Using a stable LTS version

      - name: Install ESLint and dependencies
        run: |
          npm install eslint@9.17.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0
          npm install @eslint/migrate-config

      - name: Migrate or create ESLint config
        run: |
          if [ -f .eslintrc.js ]; then
            npx @eslint/migrate-config .eslintrc.js
          elif [ -f .eslintrc.json ]; then
            npx @eslint/migrate-config .eslintrc.json
          elif [ -f .eslintrc.yaml ] || [ -f .eslintrc.yml ]; then
            npx @eslint/migrate-config .eslintrc.yaml
          else
            echo "module.exports = {
              extends: ['eslint:recommended'],
              env: { node: true, es2022: true },
              parserOptions: { ecmaVersion: 2022 }
            };" > eslint.config.js
          fi

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint . --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
