name: ESLint and Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 7 * * 2'

jobs:
  eslint-and-test:
    name: Run eslint scanning and unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install eslint@9.17.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0
          npm install mocha chai --save-dev

      - name: Create test file
        run: |
          mkdir test
          echo "const assert = require('chai').assert;
          describe('Sample Test', function() {
            it('should return true', function() {
              assert.isTrue(true);
            });
          });" > test/sample.test.js

      - name: Run ESLint
        run: npx eslint . --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Run Mocha tests
        run: npx mocha

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
