name: Mocha Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 7 * * 2'

jobs:
  test:
    name: Run Mocha tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Mocha and Chai
        run: npm install mocha chai

      - name: Create test directory and sample test
        run: |
          mkdir -p test
          echo "const assert = require('chai').assert;
          describe('Sample Test', function() {
            it('should return true', function() {
              assert.isTrue(true);
            });
          });" > test/sample.test.js

      - name: Run Mocha tests
        run: npx mocha test/**/*.js --reporter json > test-results.json

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Mocha Tests
          path: test-results.json
          reporter: mocha-json
